### ISSUE TITLE
update air monitor stations

### ISSUE THREAD

**Issue by kcwu** [g0v/env.g0v.tw#28]
Please update air monitor stations src/epa-site.csv
There are several stations changed.

New data could be found at http://data.gov.tw/node/6075

**Comment by pm5** [comment]
Looks like some stations are removed from the new list:

Dropped site: '金門金沙'
Dropped site: '金門金寧'
Dropped site: '鹿林山'
Dropped site: '馬祖東引'
Dropped site: '高雄大樹'
Dropped site: '臺中泰安'
Dropped site: '嘉義六腳'
Dropped site: '屏東玉田'
Dropped site: '臺東仁愛'
Dropped site: '三民'
Dropped site: '東沙'
Dropped site: '移動站 1'
Dropped site: '雲林義賢'
Dropped site: '阿里山'
Dropped site: '崇倫'
Dropped site: '彰化新庄'
Dropped site: '雲林旭光'
Dropped site: '雲林元長'

**Comment by pm5** [comment]
Users have to purge localStorage.

**Comment by kcwu** [comment]
asking user to purge localStorage sounds not so good. I created #30 to track that issue.
