### ISSUE TITLE
refresh localStorage if countiestopo or stations are updated

### ISSUE THREAD

**Issue by kcwu** [g0v/env.g0v.tw#30]
After updated air monitor stations #28, we should update users' localStorage as well

**Comment by pm5** [comment]
Should we add a version number to the data, or is there a simpler way to handle updates?

**Comment by kcwu** [comment]
If you don't want to think how to give version number, timestamp may be good choice.

For simpler way, refresh every 1 (or 7) days regardless the data is up to date or not :)
